#!/bin/sh
if [ -n "$" ]
then
   date=$1
else
   date=`date +%Y%m%d`
fi
cvs -z3 -d :pserver:anonymous@gnudatalanguage.cvs.sourceforge.net:/cvsroot/gnudatalanguage export -D ${date} -d gdl-0.9rc2-${date} gdl
tar cjf gdl-0.9rc2-${date}.tar.bz2 gdl-0.9rc2-${date}
