#!/bin/sh
if [ -n "$1" ]
then
   date=$1
else
   date=`date +%Y%m%d`
fi
if [ -n "$2" ]
then
   rel=$2
else
   rel=0.9.5
fi
cvs -z3 -d :pserver:anonymous@gnudatalanguage.cvs.sourceforge.net:/cvsroot/gnudatalanguage export -D ${date} -d gdl-${rel}-${date} gdl
tar cjf gdl-${rel}-${date}.tar.bz2 gdl-${rel}-${date}
